// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	_ "embed"
	"github.com/swaggo/swag"
)

//go:embed openapi.json
var docTemplate string

// OpenAPIInfo holds exported Swagger Info so clients can modify it
var OpenAPIInfo = &swag.Spec{
	Version: "1.0",
	// Host is left empty so Swagger UI uses the host serving the docs,
	// allowing the API to work behind any DNS or load balancer.
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "MQ Transfer API",
	Description:      "API para transferência de mensagens entre filas IBM MQ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(OpenAPIInfo.InstanceName(), OpenAPIInfo)
}
