basePath: /
definitions:
  models.ConnectionDetails:
    properties:
      channel:
        example: SYSTEM.DEF.SVRCONN
        type: string
      connectionName:
        example: localhost(1414)
        type: string
      password:
        example: mqpassword
        type: string
      queueManagerName:
        example: QM1
        type: string
      username:
        example: mquser
        type: string
    required:
    - channel
    - connectionName
    - queueManagerName
    type: object
  models.HealthResponse:
    properties:
      status:
        example: ok
        type: string
      version:
        example: 1.0.0
        type: string
      timestamp:
        example: 2025-06-04T00:15:30Z
        type: string
    type: object
  models.TransferRequest:
    properties:
      bufferSize:
        example: 1048576
        type: integer
      commitInterval:
        example: 10
        type: integer
      destination:
        $ref: '#/definitions/models.ConnectionDetails'
      destinationQueue:
        example: DEST.QUEUE
        type: string
      nonSharedConnection:
        example: false
        type: boolean
      source:
        $ref: '#/definitions/models.ConnectionDetails'
      sourceQueue:
        example: SOURCE.QUEUE
        type: string
    required:
    - destination
    - destinationQueue
    - source
    - sourceQueue
    type: object
  models.TransferResponse:
    properties:
      error:
        example: Failed to connect to source queue manager
        type: string
      messagesTotal:
        example: 1000
        type: integer
      messagesTransferred:
        example: 500
        type: integer
      requestId:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      status:
        example: in_progress
        type: string
    type: object
  models.TransferStatus:
    properties:
      bytesTransferred:
        example: 1048576
        type: integer
      endTime:
        example: "2025-06-04T00:16:45Z"
        type: string
      error:
        example: Failed to connect to source queue manager
        type: string
      messagesTotal:
        example: 1000
        type: integer
      messagesTransferred:
        example: 500
        type: integer
      requestId:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      startTime:
        example: "2025-06-04T00:15:30Z"
        type: string
      status:
        example: in_progress
        type: string
    type: object
host: ""
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API para transferência de mensagens entre filas IBM MQ
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MQ Transfer API
  version: "1.0"
paths:
  /api/v1/health:
    get:
      description: Retorna informacoes de saude da aplicacao
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HealthResponse'
      summary: Health Check
      tags:
      - health
  /api/v1/transfer:
    post:
      consumes:
      - application/json
      description: Inicia uma transferência de mensagens de uma fila MQ para outra
      parameters:
      - description: Detalhes da transferência
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.TransferRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Transferência iniciada
          schema:
            $ref: '#/definitions/models.TransferResponse'
        "400":
          description: Erro na requisição
          schema:
            $ref: '#/definitions/models.TransferResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/models.TransferResponse'
      summary: Iniciar transferência de mensagens MQ
      tags:
      - transfer
  /api/v1/transfer/{requestId}:
    get:
      description: Retorna o status atual de uma transferência de mensagens
      parameters:
      - description: ID da requisição de transferência
        in: path
        name: requestId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Status da transferência
          schema:
            $ref: '#/definitions/models.TransferStatus'
        "404":
          description: Transferência não encontrada
          schema:
            $ref: '#/definitions/models.TransferResponse'
      summary: Obter status da transferência
      tags:
      - transfer
  /api/v1/transfer/{requestId}/cancel:
    post:
      description: Cancela uma transferência de mensagens que está em andamento
      parameters:
      - description: ID da requisição de transferência
        in: path
        name: requestId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Transferência cancelada
          schema:
            $ref: '#/definitions/models.TransferResponse'
        "400":
          description: Transferência já concluída
          schema:
            $ref: '#/definitions/models.TransferResponse'
        "404":
          description: Transferência não encontrada
          schema:
            $ref: '#/definitions/models.TransferResponse'
      summary: Cancelar uma transferência em andamento
      tags:
      - transfer
  /api/v1/transfers:
    get:
      description: Retorna uma lista com todas as transferências e seus status
      produces:
      - application/json
      responses:
        "200":
          description: Lista de transferências
          schema:
            items:
              $ref: '#/definitions/models.TransferStatus'
            type: array
      summary: Listar todas as transferências
      tags:
      - transfer
schemes:
- http
swagger: "2.0"
