// Code generated by MockGen. DO NOT EDIT.
// Source: transferstore/store.go

// Package mock_transferstore is a generated GoMock package.
package mock_transferstore

import (
	transferstore "mq-forwarder-go/transferstore"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTransferStore is a mock of TransferStore interface.
type MockTransferStore struct {
	ctrl     *gomock.Controller
	recorder *MockTransferStoreMockRecorder
}

// MockTransferStoreMockRecorder is the mock recorder for MockTransferStore.
type MockTransferStoreMockRecorder struct {
	mock *MockTransferStore
}

// NewMockTransferStore creates a new mock instance.
func NewMockTransferStore(ctrl *gomock.Controller) *MockTransferStore {
	mock := &MockTransferStore{ctrl: ctrl}
	mock.recorder = &MockTransferStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferStore) EXPECT() *MockTransferStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransferStore) Create(req transferstore.TransferRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransferStoreMockRecorder) Create(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransferStore)(nil).Create), req)
}

// GetByID mocks base method.
func (m *MockTransferStore) GetByID(id string) (transferstore.TransferRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(transferstore.TransferRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransferStoreMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransferStore)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockTransferStore) List(params transferstore.ListParams) ([]transferstore.TransferRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", params)
	ret0, _ := ret[0].([]transferstore.TransferRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransferStoreMockRecorder) List(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransferStore)(nil).List), params)
}

// UpdateProgress mocks base method.
func (m *MockTransferStore) UpdateProgress(id string, messagesTransferred, bytesTransferred int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgress", id, messagesTransferred, bytesTransferred)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockTransferStoreMockRecorder) UpdateProgress(id, messagesTransferred, bytesTransferred interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockTransferStore)(nil).UpdateProgress), id, messagesTransferred, bytesTransferred)
}

// UpdateStatus mocks base method.
func (m *MockTransferStore) UpdateStatus(id, status string, endTime *time.Time, errorMsg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status, endTime, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTransferStoreMockRecorder) UpdateStatus(id, status, endTime, errorMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTransferStore)(nil).UpdateStatus), id, status, endTime, errorMsg)
}
